# Generated by Django 5.2.6 on 2025-09-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_sessionplayer_chat_gpt_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='token_cents_value',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
    ]
