# Generated by Django 5.2.6 on 2025-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_remove_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetground',
            name='render_order',
            field=models.IntegerField(default=0, verbose_name='Render Order'),
        ),
    ]
