# Generated by Django 5.2.6 on 2025-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_add_render_order_to_parameter_set_ground'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetground',
            name='enable_clipping',
            field=models.BooleanField(default=False, verbose_name='Enable Clipping'),
        ),
    ]
