# Generated by Django 5.2.6 on 2025-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_add_enable_clipping_to_parameter_set_ground'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=False, verbose_name='Enable Chat'),
        ),
    ]
