# Generated by Django 5.2.6 on 2025-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_add_enable_chat_to_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='orchard_apple_location',
            field=models.CharField(blank=True, default='100,150', max_length=100, null=True, verbose_name='Apple Orchard Location'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='orchard_orange_location',
            field=models.CharField(blank=True, default='300,150', max_length=100, null=True, verbose_name='Orange Orchard Location'),
        ),
    ]
