# Generated by Django 5.2.6 on 2025-10-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_parameterset_orchard_apple_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='cool_down_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_length',
        ),
    ]
