# Generated by Django 5.2.6 on 2025-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_remove_parameterset_cool_down_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='retailer_budget',
            field=models.IntegerField(default=1000, verbose_name='Retailer Budget (¢)'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='wholesaler_budget',
            field=models.IntegerField(default=1000, verbose_name='Wholesaler Budget (¢)'),
        ),
    ]
