# Generated by Django 5.2.6 on 2025-10-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_parameterset_retailer_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(default=1, verbose_name='Period Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Period',
                'verbose_name_plural': 'Parameter Set Periods',
                'ordering': ['id'],
            },
        ),
    ]
