# Generated by Django 5.2.7 on 2025-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_parametersetperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetperiod',
            options={'ordering': ['period_number'], 'verbose_name': 'Parameter Set Period', 'verbose_name_plural': 'Parameter Set Periods'},
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='factory_apple_price',
            field=models.IntegerField(default=50, verbose_name='Factory Apple Price (¢)'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='orchard_orange_price',
            field=models.IntegerField(default=30, verbose_name='Factory Orange Price (¢)'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='retailer_budget',
            field=models.IntegerField(default=1000, verbose_name='Retailer Budget (¢)'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='wholesale_apple_price',
            field=models.IntegerField(default=100, verbose_name='Wholesale Apple Price (¢)'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='wholesale_orange_price',
            field=models.IntegerField(default=80, verbose_name='Wholesale Orange Price (¢)'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='wholsaler_budget',
            field=models.IntegerField(default=1000, verbose_name='Wholesaler Budget (¢)'),
        ),
    ]
