# Generated by Django 5.2.7 on 2025-10-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_parametersetperiod_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='wholsaler_budget',
            new_name='wholesaler_budget',
        ),
    ]
