# Generated by Django 5.2.7 on 2025-10-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_rename_wholsaler_budget_parametersetperiod_wholesaler_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='retailer_budget',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='wholesaler_budget',
        ),
    ]
