# Generated by Django 5.2.7 on 2025-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_remove_parameterset_retailer_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='apple_tray_capacity',
            field=models.IntegerField(default=100, verbose_name='Apple Tray Capacity'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='apple_tray_starting_inventory',
            field=models.IntegerField(default=0, verbose_name='Apple Tray Starting Inventory'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='orange_tray_capacity',
            field=models.IntegerField(default=100, verbose_name='Orange Tray Capacity'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='orange_tray_starting_inventory',
            field=models.IntegerField(default=0, verbose_name='Orange Tray Starting Inventory'),
        ),
    ]
