# Generated by Django 5.2.6 on 2025-10-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_add_tray_fields_to_parameter_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='factory_orange_price',
            new_name='orchard_orange_price',
        ),
    ]
