# Generated by Django 5.2.6 on 2025-10-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_rename_orchard_orange_price_parametersetperiod_factory_orange_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='factory_apple_price',
            new_name='orchard_apple_price',
        ),
    ]
