# Generated by Django 5.2.6 on 2025-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_rename_factory_apple_price_parametersetperiod_orchard_apple_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='apple_tray_location',
            field=models.CharField(blank=True, default='700,150', max_length=100, null=True, verbose_name='Apple Tray Location'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='orange_tray_location',
            field=models.CharField(blank=True, default='500,150', max_length=100, null=True, verbose_name='Orange Tray Location'),
        ),
    ]
