# Generated by Django 5.2.7 on 2025-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_parameterset_apple_tray_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='register_location',
            field=models.CharField(blank=True, default='200,250', max_length=100, null=True, verbose_name='Register Location'),
        ),
    ]
