# Generated by Django 5.2.7 on 2025-10-16 19:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_add_register_location_to_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='consumer_prices',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
