# Generated by Django 5.2.7 on 2025-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_parameterset_consumer_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='consumer_location',
            field=models.CharField(blank=True, default='250,350', max_length=100, null=True, verbose_name='Consumer Location'),
        ),
    ]
