# Generated by Django 5.2.8 on 2025-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_add_consumer_location_to_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='end_game_choice',
            field=models.CharField(choices=[('Off', 'Off'), ('Steal', 'Steal'), ('No Price', 'No Price')], default='Off', max_length=20, verbose_name='End Game Choice'),
        ),
    ]
