# Generated by Django 5.2.8 on 2025-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_add_end_game_choice_to_parameter_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='orchard_apple_price',
            field=models.IntegerField(default=50, verbose_name='Orchard Apple Price (¢)'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='orchard_orange_price',
            field=models.IntegerField(default=30, verbose_name='Orchard Orange Price (¢)'),
        ),
    ]
