# Generated by Django 5.2.8 on 2025-11-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_parametersetperiod_orchard_apple_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='consumer_prices',
            new_name='customer_prices',
        ),
    ]
