# Generated by Django 5.2.8 on 2025-11-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_rename_consumer_prices_parameterset_customer_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['period_number', 'time_remaining'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='break_frequency',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='break_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_length',
        ),
    ]
