# Generated by Django 5.2.8 on 2025-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='max_fruit',
            field=models.IntegerField(default=100, verbose_name='Max Fruit'),
        ),
    ]
