# Generated by Django 5.2.8 on 2025-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_parametersetperiod_max_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='max_fruit',
            field=models.IntegerField(default=10, verbose_name='Max Fruit'),
        ),
    ]
