# Generated by Django 5.2.8 on 2025-12-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_alter_parametersetperiod_max_fruit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='retailer_budget',
            new_name='reseller_budget',
        ),
    ]
