# Generated by Django 5.2.8 on 2025-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_rename_retailer_budget_parametersetperiod_reseller_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='reseller_budget',
            field=models.IntegerField(default=1000, verbose_name='Reseller Budget (¢)'),
        ),
    ]
