# Generated by Django 5.2.8 on 2025-12-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_parametersetperiod_reseller_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='customer_prices',
            new_name='buyer_prices',
        ),
    ]
