# Generated by Django 5.2.8 on 2025-12-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_rename_customer_prices_parameterset_buyer_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='consumer_location',
            new_name='buyer_location',
        ),
    ]
