# Generated by Django 5.2.11 on 2026-03-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_rename_consumer_location_parameterset_buyer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='apple_tray_capacity',
            field=models.IntegerField(default=10, verbose_name='Apple Tray Capacity'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='orange_tray_capacity',
            field=models.IntegerField(default=10, verbose_name='Orange Tray Capacity'),
        ),
    ]
