# Generated by Django 5.2.11 on 2026-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_parameterset_apple_tray_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='show_help_buttons',
            field=models.BooleanField(default=True, verbose_name='Show Help Buttons'),
        ),
    ]
